In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [2]:
a

array([1, 2, 3])

In [3]:
b = np.array([
    (1.5, 2, 3),
    (4, 5, 6)
], dtype=float)

In [4]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c = np.array([
    [(1.5, 2, 3), (4, 5, 6)],
    [(3, 2, 1), (4, 5, 6)]
], dtype=float

_IncompleteInputError: incomplete input (93990664.py, line 4)

In [6]:
c = np.array([
    [(1.5, 2, 3), (4, 5, 6)],
    [(3, 2, 1), (4, 5, 6)]
], dtype=float)


In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [8]:
zeros_array = np.zeros((3, 4))
print("\n3x4 zeros array:\n", zeros_array)


3x4 zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
ones_array = np.ones((2, 3, 4), dtype=np.int16)
print("\n2x3x4 ones array (int16):\n", ones_array)


2x3x4 ones array (int16):
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [10]:
range_array = np.arange(10, 25, 5)
print("\nValues from 10 to 25 with step 5:\n", range_array)


Values from 10 to 25 with step 5:
 [10 15 20]


In [11]:
linspace_array = np.linspace(0, 2, 9)
print("\n9 evenly spaced values between 0 and 2:\n", linspace_array)


9 evenly spaced values between 0 and 2:
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [12]:
constant_array = np.full((2, 2), 7)
print("\n2x2 constant array (7):\n", constant_array)



2x2 constant array (7):
 [[7 7]
 [7 7]]


In [13]:
identity_matrix = np.eye(2)
random_matrix = np.random.random((2, 2))

In [14]:
print("\n2x2 Identity Matrix:\n", identity_matrix)
print("\n2x2 Random Matrix:\n", random_matrix)



2x2 Identity Matrix:
 [[1. 0.]
 [0. 1.]]

2x2 Random Matrix:
 [[0.1428101  0.19355799]
 [0.71458645 0.52417141]]


In [15]:
for name, arr in zip(['a', 'b', 'c'], [a, b, c]):
    print(f"\nArray {name}:")
    print("Shape:", arr.shape)
    print("Dimensions (ndim):", arr.ndim)
    print("Size:", arr.size)



Array a:
Shape: (3,)
Dimensions (ndim): 1
Size: 3

Array b:
Shape: (2, 3)
Dimensions (ndim): 2
Size: 6

Array c:
Shape: (2, 2, 3)
Dimensions (ndim): 3
Size: 12


In [16]:
print("\nArray b dtype:", b.dtype)
print("Array b dtype name:", b.dtype.name)


Array b dtype: float64
Array b dtype name: float64


In [17]:
b_int = b.astype(int)
print("Array b converted to integers:\n", b_int)


Array b converted to integers:
 [[1 2 3]
 [4 5 6]]


In [18]:
print("\na + b:\n", a + b)
print("\na - b:\n", a - b)


a + b:
 [[2.5 4.  6. ]
 [5.  7.  9. ]]

a - b:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [19]:
print("\nb * b:\n", b * b)
print("\nb / b:\n", b / b)



b * b:
 [[ 2.25  4.    9.  ]
 [16.   25.   36.  ]]

b / b:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print("\nSquare root of b:\n", np.sqrt(b))



Square root of b:
 [[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [21]:
print("\nSum:", np.sum(b))
print("Minimum:", np.min(b))
print("Maximum:", np.max(b))
print("Cumulative Sum:", np.cumsum(b))
print("Mean:", np.mean(b))
print("Median:", np.median(b))
print("Standard Deviation:", np.std(b))


Sum: 21.5
Minimum: 1.5
Maximum: 6.0
Cumulative Sum: [ 1.5  3.5  6.5 10.5 15.5 21.5]
Mean: 3.5833333333333335
Median: 3.5
Standard Deviation: 1.5920810978785667
